spring.config.import=optional:classpath:application-secret.properties
spring.application.name=campus_backend
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/campus_project
spring.datasource.username=postgres
spring.datasource.password=dishika@31
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security.oauth2=TRACE


